chill=https://www.youtube.com/watch?v=ZX_mvoY_Hg0&list=PL08ytyBKu7cp10v7cIdGkwLGk6sb_Vcw-
# Playlists from uldrens0v
l9=https://www.youtube.com/playlist?list=PLcMzwcDtl5lrVPJAgWX9iVs7CFxWCxKaO
god-bless-me=https://www.youtube.com/playlist?list=PLcMzwcDtl5lrBj9Li0Q8_0RSV5s5gddcW
musica=https://www.youtube.com/playlist?list=PLcMzwcDtl5lqciH2-pJeEtMLNc7NfFN64

# SoundCloud playlists
sc=https://soundcloud.com/hustleraphiphop/sets/new-plugg-music-plugg
# Bandcamp albums
bc=https://c418.bandcamp.com/album/minecraft-volume-alpha

# Spotify playlists (requires spotdl)
lofi-spotify=https://open.spotify.com/playlist/0vvXsWCC9xrXsKd4FyS8kM
chill-hits-spotify=https://open.spotify.com/playlist/37i9dQZF1DX4WYpdgoIcn6
